package com.example.ui

enum class Language {
    ENGLISH, HINDI, BENGALI, TELUGU, MARATHI, TAMIL, GUJARATI, URDU, KANNADA, MALAYALAM, PUNJABI
}

object Loc {
    private val en = mapOf(
        "app_title" to "Credit Book",
        "receivable" to "Total Receivable (You Get)",
        "payable" to "Total Payable (You Give)",
        "today_tx" to "Today's Transactions",
        "monthly_summary" to "Monthly Summary",
        "quick_add" to "Quick Add",
        "add_customer" to "Add Customer",
        "add_supplier" to "Add Supplier",
        "dashboard_tab" to "Dashboard",
        "customers_tab" to "Customers",
        "suppliers_tab" to "Suppliers",
        "inventory_tab" to "Inventory",
        "billing_tab" to "Billing",
        "profile_tab" to "Shop Profile",
        "customer_name" to "Customer Name",
        "supplier_name" to "Supplier Name",
        "phone_number" to "Mobile Number",
        "address" to "Address",
        "save" to "Save",
        "cancel" to "Cancel",
        "delete" to "Delete",
        "edit" to "Edit",
        "udhar_khata" to "Udhar Khata Ledger",
        "give_credit" to "Give Credit (Out / -)",
        "receive_payment" to "Receive Pay (In / +)",
        "remaining_bal" to "Outstanding Balance",
        "amount" to "Amount (₹)",
        "notes" to "Details (Items / Notes)",
        "add_transaction" to "Add Transaction",
        "search_hint" to "Search by name or number...",
        "no_customers" to "No customers added yet.",
        "no_suppliers" to "No suppliers added yet.",
        "no_transactions" to "No transactions recorded yet.",
        "record_purchase" to "Record Purchase (-)",
        "record_payment" to "Record Payment (+)",
        "stock_alert" to "Low Stock Alert!",
        "add_product" to "Add New Product",
        "product_name" to "Product Name",
        "category" to "Category / Tag",
        "selling_price" to "Price (₹)",
        "stock_qty" to "Opening Stock Qty",
        "low_stock_limit" to "Minimum Stock Threshold",
        "barcode" to "Barcode / SKU (Optional)",
        "total_stock" to "Total Items",
        "gst_billing" to "GST Billing System",
        "create_invoice" to "Generate Invoice",
        "invoice_no" to "Invoice Number",
        "gst_rate" to "GST Rate (%)",
        "include_gst" to "GST Bill (Include)",
        "total_amount" to "SubTotal",
        "share_whatsapp" to "Share Bill via WhatsApp",
        "share_sms" to "Share Reminder via SMS",
        "reminder_heading" to "Payment Reminder",
        "business_name" to "Business / Shop Name",
        "upi_id" to "UPI ID (e.g. shop@okaxis)",
        "gstin" to "GSTIN (Optional)",
        "profile_setting" to "Business Settings",
        "net_balance" to "Net Balance",
        "upi_qr" to "Your UPI Custom QR Code",
        "reminder_text" to "Dear customer, your outstanding payment of ₹%s is due. Please pay using the details below. Thank you!",
        "switch_lang" to "भाषा बदलें / English",
        "hindi" to "हिंदी",
        "english" to "English",
        "gst_charge" to "GST Tax Amount",
        "net_payable" to "Net Bill Payable",
        "unpaid" to "Outstanding",
        "paid" to "Settled"
    )

    private val hi = mapOf(
        "app_title" to "Credit Book",
        "receivable" to "कुल पाना (ग्राहक से)",
        "payable" to "कुल देना (सप्लायर को)",
        "today_tx" to "आज का लेन-देन",
        "monthly_summary" to "मासिक सारांश",
        "quick_add" to "ग्राहक जोड़ें",
        "add_customer" to "नया ग्राहक जोड़ें",
        "add_supplier" to "नया सप्लायर जोड़ें",
        "dashboard_tab" to "डैशबोर्ड",
        "customers_tab" to "ग्राहक खाता",
        "suppliers_tab" to "सप्लायर",
        "inventory_tab" to "स्टॉक माल",
        "billing_tab" to "बिलिंग/इनवॉइस",
        "profile_tab" to "दुकान प्रोफाइल",
        "customer_name" to "ग्राहक का नाम",
        "supplier_name" to "सप्लायर का नाम",
        "phone_number" to "मोबाइल नंबर",
        "address" to "दुकान/घर का पता",
        "save" to "सुरक्षित करें",
        "cancel" to "रद्द करें",
        "delete" to "हटाएं",
        "edit" to "बदलें",
        "udhar_khata" to "उधार खाता बही",
        "give_credit" to "उधार दिया (Out / -)",
        "receive_payment" to "जमा पाया (In / +)",
        "remaining_bal" to "कुल शेष बकाया",
        "amount" to "रकम (₹)",
        "notes" to "सामान का विवरण / नोट",
        "add_transaction" to "लेन-देन जोड़ें",
        "search_hint" to "नाम या नंबर से खोजें...",
        "no_customers" to "अभी तक कोई ग्राहक नहीं जोड़ा गया है।",
        "no_suppliers" to "अभी तक कोई सप्लायर नहीं जोड़ा गया है।",
        "no_transactions" to "कोई लेन-देन दर्ज नहीं है।",
        "record_purchase" to "उधार ख़रीदा (-) ",
        "record_payment" to "पेमेंट दिया (+)",
        "stock_alert" to "स्टॉक अलर्ट (कम माल है)!",
        "add_product" to "नया सामान जोड़ें",
        "product_name" to "सामान/आइटम का नाम",
        "category" to "श्रेणी (कैटेगरी)",
        "selling_price" to "विक्रय मूल्य (₹)",
        "stock_qty" to "शुरुआती स्टॉक संख्या",
        "low_stock_limit" to "कम से कम लिमिट (अलर्ट)",
        "barcode" to "बारकोड (वैकल्पिक)",
        "total_stock" to "कुल सामान उपलब्ध",
        "gst_billing" to "जीएसटी बिलिंग",
        "create_invoice" to "इनवॉइस तैयार करें",
        "invoice_no" to "बिल / इनवॉइस नंबर",
        "gst_rate" to "GST टैक्स दर (%)",
        "include_gst" to "GST टैक्स जोड़ें",
        "total_amount" to "मुख्य मूल्य (SubTotal)",
        "share_whatsapp" to "व्हाट्सएप पर शेयर करें",
        "share_sms" to "एसएमएस (SMS) रिमाइंडर",
        "reminder_heading" to "भुगतान सूचना रिमाइंडर",
        "business_name" to "दुकान या व्यापार का नाम",
        "upi_id" to "यूपीआई आईडी (UPI ID)",
        "gstin" to "GSTIN नंबर (वैकल्पिक)",
        "profile_setting" to "माई शॉप प्रोफाइल",
        "net_balance" to "शुद्ध बकाया राशि",
        "upi_qr" to "आपका पेमेंट यूपीआई QR कोड",
        "reminder_text" to "प्रिय ग्राहक, आपका ₹%s का बकाया भुगतान बाकी है। कृपया जल्द ही भुगतान करें। धन्यवाद!",
        "switch_lang" to "Change Language / हिंदी",
        "hindi" to "हिंदी",
        "english" to "English",
        "gst_charge" to "जीएसटी टैक्स राशि",
        "net_payable" to "कुल देय राशि (₹)",
        "unpaid" to "बाकी बकाया",
        "paid" to "चुकाया"
    )

    // Bengali Translations
    private val bn = mapOf(
        "app_title" to "স্মার্ট খাতা প্রো",
        "receivable" to "মোট পাওনা (আপনি পাবেন)",
        "payable" to "মোট দেনা (আপনি দেবেন)",
        "today_tx" to "আজকের লেনদেন",
        "monthly_summary" to "মাসিক সারাংশ",
        "quick_add" to "গ্রাহক যোগ করুন",
        "add_customer" to "নতুন গ্রাহক যোগ করুন",
        "add_supplier" to "নতুন সরবরাহকারী যোগ করুন",
        "dashboard_tab" to "ড্যাশবোর্ড",
        "customers_tab" to "গ্রাহক খাতা",
        "suppliers_tab" to "সরবরাহকারী",
        "inventory_tab" to "স্টক তালিকা",
        "billing_tab" to "বিলিং ও ইনভয়েস",
        "profile_tab" to "দোকান প্রোফাইল",
        "customer_name" to "গ্রাহকের নাম",
        "supplier_name" to "সরবরাহকারীর নাম",
        "phone_number" to "মোবাইল নম্বর",
        "address" to "ঠিকানা",
        "save" to "সংরক্ষণ করুন",
        "cancel" to "বাতিল",
        "delete" to "মুছে ফেলুন",
        "edit" to "সম্পাদনা",
        "udhar_khata" to "ধার খাতা লেজার",
        "give_credit" to "ধার দেওয়া (আউট / -)",
        "receive_payment" to "টাকা গ্রহণ (ইন / +)",
        "remaining_bal" to "অবশিষ্ট বকেয়া",
        "amount" to "টাকা (₹)",
        "notes" to "বিবরণ (আইটেম / নোট)",
        "add_transaction" to "লেনদেন যোগ করুন",
        "search_hint" to "নাম বা নম্বর দিয়ে খুঁজুন...",
        "no_customers" to "কোন গ্রাহক যোগ করা হয়নি।",
        "no_suppliers" to "কোন সরবরাহকারী যোগ করা হয়নি।",
        "no_transactions" to "কোন লেনদেন রেকর্ড করা হয়নি।",
        "record_purchase" to "ক্রয় রেকর্ড (-)",
        "record_payment" to "পেমেন্ট রেকর্ড (+)",
        "stock_alert" to "স্বল্প স্টক সতর্কতা!",
        "add_product" to "নতুন পণ্য যোগ করুন",
        "product_name" to "পণ্যের নাম",
        "category" to "ক্যাটাগরি",
        "selling_price" to "মূল্য (₹)",
        "stock_qty" to "ওপেনিং স্টক",
        "low_stock_limit" to "ন্যূনতম স্টক থ্রেশহোল্ড",
        "barcode" to "বারকোড (ঐচ্ছিক)",
        "total_stock" to "মোট আইটেম",
        "gst_billing" to "জিএসটি বিলিং",
        "create_invoice" to "ইনভয়েস তৈরি করুন",
        "invoice_no" to "ইনভয়েস নম্বর",
        "gst_rate" to "জিএসটি হার (%)",
        "include_gst" to "জিএসটি অন্তর্ভুক্ত করুন",
        "total_amount" to "উপমোট",
        "share_whatsapp" to "হোয়াটসঅ্যাপে শেয়ার করুন",
        "share_sms" to "এসএমএস রিমাইন্ডার",
        "reminder_heading" to "পেমেন্ট রিমাইন্ডার",
        "business_name" to "ব্যবসার নাম",
        "upi_id" to "ইউপিআই আইডি",
        "gstin" to "জিএসটিআইএন (ঐচ্ছিক)",
        "profile_setting" to "ব্যবসা সেটিংস",
        "net_balance" to "নেট ব্যালেন্স",
        "upi_qr" to "ইউপিআই কিউআর কোড",
        "reminder_text" to "প্রিয় গ্রাহক, আপনার ₹%s বকেয়া পেমেন্ট বাকি আছে। অনুগ্রহ করে নিচের বিবরণ ব্যবহার করে পরিশোধ করুন। ধন্যবাদ!",
        "switch_lang" to "ভাষা পরিবর্তন",
        "gst_charge" to "জিএসটি ট্যাক্স",
        "net_payable" to "মোট প্রদেয়",
        "unpaid" to "বকেয়া",
        "paid" to "পরিশোধিত"
    )

    // Telugu Translations
    private val te = mapOf(
        "app_title" to "స్మార్ట్ ఖాతా ప్రో",
        "receivable" to "మొత్తం రావలసినవి (మీకు వచ్చేవి)",
        "payable" to "మొత్తం చెల్లించవలసినవి (మీరు ఇచ్చేవి)",
        "today_tx" to "ఈరోజు లావాదేవీలు",
        "monthly_summary" to "నెలవారీ సారాంశం",
        "quick_add" to "కస్టమర్‌ని జోడించు",
        "add_customer" to "కొత్త కస్టమర్‌ని జోడించు",
        "add_supplier" to "కొత్త సప్లయర్‌ని జోడించు",
        "dashboard_tab" to "డాష్‌బోర్డ్",
        "customers_tab" to "కస్టమర్ ఖాతా",
        "suppliers_tab" to "సప్లయర్స్",
        "inventory_tab" to "ఇన్వెంటరీ",
        "billing_tab" to "బిల్లింగ్ & ఇన్వాయిస్",
        "profile_tab" to "షాప్ ప్రొఫైల్",
        "customer_name" to "కస్టమర్ పేరు",
        "supplier_name" to "సప్లయర్ పేరు",
        "phone_number" to "మొబైల్ సంఖ్య",
        "address" to "చిరునామా",
        "save" to "సేవ్ చేయి",
        "cancel" to "రద్దు చేయి",
        "delete" to "తొలగించు",
        "edit" to "సవరించు",
        "udhar_khata" to "ఉధార్ ఖాతా లెడ్జర్",
        "give_credit" to "అప్పు ఇవ్వండి (అవుట్ / -)",
        "receive_payment" to "పేమెంట్ తీసుకోండి (ఇన్ / +)",
        "remaining_bal" to "మిగిలిన బ్యాలెన్స్",
        "amount" to "మొత్తం (₹)",
        "notes" to "వివరాలు (వస్తువులు / నోట్స్)",
        "add_transaction" to "లావాదేవీని జోడించు",
        "search_hint" to "పేరు లేదా నంబర్‌తో వెతకండి...",
        "no_customers" to "ఇంకా కస్టమర్లను జోడించలేదు.",
        "no_suppliers" to "ఇంకా సప్లయర్లను జోడించలేదు.",
        "no_transactions" to "ఇంకా లావాదేవీలు నమోదు చేయలేదు.",
        "record_purchase" to "కొనుగోలు రికార్డు (-)",
        "record_payment" to "చెల్లింపు రికార్డు (+)",
        "stock_alert" to "స్టాక్ అలర్ట్!",
        "add_product" to "కొత్త వస్తువును జోడించు",
        "product_name" to "వస్తువు పేరు",
        "category" to "వర్గం",
        "selling_price" to "ధర (₹)",
        "stock_qty" to "ప్రారంభ స్టాక్",
        "low_stock_limit" to "కనిష్ట స్టాక్ పరిమితి",
        "barcode" to "బార్‌కోడ్ (ఆప్షనల్)",
        "total_stock" to "మొత్తం స్టాక్",
        "gst_billing" to "జీఎస్టీ బిల్లింగ్",
        "create_invoice" to "ఇన్వాయిస్ సృష్టించు",
        "invoice_no" to "ఇన్వాయిస్ సంఖ్య",
        "gst_rate" to "జీఎస్టీ రేట్ (%)",
        "include_gst" to "జీఎస్టీని చేర్చండి",
        "total_amount" to "సబ్‌టోటల్",
        "share_whatsapp" to "వాట్సాప్ ద్వారా షేర్ చేయి",
        "share_sms" to "SMS రిమైండర్",
        "reminder_heading" to "చెల్లింపు రిమైండర్",
        "business_name" to "వ్యాపార నామం",
        "upi_id" to "UPI ఐడీ",
        "gstin" to "GSTIN (ఆప్షనల్)",
        "profile_setting" to "వ్యాపార సెట్టింగులు",
        "net_balance" to "నికర నిల్వ",
        "upi_qr" to "UPI QR కోడ్",
        "reminder_text" to "ప్రియమైన కస్టమర్, మీ బకాయి మొత్తం ₹%s చెల్లించాల్సి ఉంది. దయచేసి క్రింది వివరాలను ఉపయోగించి చెల్లించండి. ధన్యవాదాలు!",
        "switch_lang" to "భాషను మార్చండి",
        "gst_charge" to "జీఎస్టీ పన్ను",
        "net_payable" to "మొత్తం చెల్లించవలసినది",
        "unpaid" to "బకాయి",
        "paid" to "చెల్లించినవి"
    )

    // Marathi Translations
    private val mr = mapOf(
        "app_title" to "Credit Book",
        "receivable" to "एकूण येणे (ग्राहकांकडून)",
        "payable" to "एकूण देणे (सप्लायर्सना)",
        "today_tx" to "आजचे व्यवहार",
        "monthly_summary" to "मासिक सारांश",
        "quick_add" to "ग्राहक जोडा",
        "add_customer" to "नवीन ग्राहक जोडा",
        "add_supplier" to "नवीन सप्लायर जोडा",
        "dashboard_tab" to "डॅशबोर्ड",
        "customers_tab" to "ग्राहक खाते",
        "suppliers_tab" to "सप्लायर्स",
        "inventory_tab" to "स्टॉक माल",
        "billing_tab" to "बिलिंग आणि इनव्हॉइस",
        "profile_tab" to "दुकान प्रोफाईल",
        "customer_name" to "ग्राहकाचे नाव",
        "supplier_name" to "सप्लायरचे नाव",
        "phone_number" to "मोबाईल नंबर",
        "address" to "पत्ता",
        "save" to "सुरक्षित करा",
        "cancel" to "रद्द करा",
        "delete" to "हटवा",
        "edit" to "बदला",
        "udhar_khata" to "उधारी खाते बही",
        "give_credit" to "उधार दिले (बाहेर / -)",
        "receive_payment" to "जमा मिळाले (आत / +)",
        "remaining_bal" to "उर्वरित बाकी",
        "amount" to "रक्कम (₹)",
        "notes" to "तपशील (वस्तू / नोट्स)",
        "add_transaction" to "व्यवहार जोडा",
        "search_hint" to "नाव किंवा नंबर शोधा...",
        "no_customers" to "अद्याप कोणी ग्राहक जोडला नाही.",
        "no_suppliers" to "अद्याप कोणी सप्लायर जोडला नाही.",
        "no_transactions" to "अद्याप कोणताही व्यवहार नोंदवला नाही.",
        "record_purchase" to "खरेदी नोंदवा (-)",
        "record_payment" to "पेमेंट नोंदवा (+)",
        "stock_alert" to "कमी स्टॉक अलर्ट!",
        "add_product" to "नवीन उत्पादन जोडा",
        "product_name" to "उत्पादनाचे नाव",
        "category" to "श्रेणी",
        "selling_price" to "किंमत (₹)",
        "stock_qty" to "सुरुवातीचा स्टॉक संख्या",
        "low_stock_limit" to "किमान स्टॉक मर्यादा",
        "barcode" to "बारकोड (वैकल्पिक)",
        "total_stock" to "एकूण स्टॉक",
        "gst_billing" to "जीएसटी बिलिंग",
        "create_invoice" to "इनव्हॉइस तयार करा",
        "invoice_no" to "इनव्हॉइस नंबर",
        "gst_rate" to "GST दर (%)",
        "include_gst" to "GST समाविष्ट करा",
        "total_amount" to "एकूण मूल्य (SubTotal)",
        "share_whatsapp" to "व्हॉट्सॲपवर शेअर करा",
        "share_sms" to "SMS रिमाइंडर",
        "reminder_heading" to "पेमेंट रिमाइंडर",
        "business_name" to "व्यवसायाचे नाव",
        "upi_id" to "UPI आयडी",
        "gstin" to "GSTIN (वैकल्पिक)",
        "profile_setting" to "व्यवसाय सेटिंग्स",
        "net_balance" to "निव्वळ शिल्लक",
        "upi_qr" to "UPI QR कोड",
        "reminder_text" to "प्रिय ग्राहक, आपले ₹%s पेमेंट येणे बाकी आहे. कृपया खालील डिटेल्स वापरून पेमेंट करा. धन्यवाद!",
        "switch_lang" to "भाषा बदला",
        "gst_charge" to "जीएसटी टॅक्स",
        "net_payable" to "एकूण देय रक्कम",
        "unpaid" to "बाकी",
        "paid" to "पूर्ण भरले"
    )

    // Tamil Translations
    private val ta = mapOf(
        "app_title" to "ஸ்மார்ட் காதா ப்ரோ",
        "receivable" to "மொத்த வரவு (உங்களுக்கு வரவேண்டியது)",
        "payable" to "மொத்த பற்று (நீங்கள் கொடுக்கவேண்டியது)",
        "today_tx" to "இன்றைய பரிவர்த்தனைகள்",
        "monthly_summary" to "மாதாந்திர சுருக்கம்",
        "quick_add" to "வாடிக்கையாளர் சேர்",
        "add_customer" to "புதிய வாடிக்கையாளர் சேர்",
        "add_supplier" to "புதிய சப்ளையர் சேர்",
        "dashboard_tab" to "டாஷ்போர்டு",
        "customers_tab" to "வாடிக்கையாளர் கணக்கு",
        "suppliers_tab" to "சப்ளையர்கள்",
        "inventory_tab" to "சரக்குகள்",
        "billing_tab" to "பில்லிங் & இன்வாய்ஸ்",
        "profile_tab" to "கடை சுயவிவரம்",
        "customer_name" to "வாடிக்கையாளர் பெயர்",
        "supplier_name" to "சப்ளையர் பெயர்",
        "phone_number" to "மொபைல் எண்",
        "address" to "முகவரி",
        "save" to "சேமி",
        "cancel" to "ரத்து செய்",
        "delete" to "நீக்கு",
        "edit" to "திருத்து",
        "udhar_khata" to "கடன் கணக்கு லெட்ஜர்",
        "give_credit" to "கடன் கொடு (அவுட் / -)",
        "receive_payment" to "பணம் பெறு (இன் / +)",
        "remaining_bal" to "மீதமுள்ள இருப்பு",
        "amount" to "தொகை (₹)",
        "notes" to "விவரங்கள் (பொருட்கள் / குறிப்புகள்)",
        "add_transaction" to "பரிவர்த்தனை சேர்",
        "search_hint" to "பெயர் அல்லது எண்ணில் தேடுக...",
        "no_customers" to "வாடிக்கையாளர்கள் யாரும் சேர்க்கப்படவில்லை.",
        "no_suppliers" to "சப்ளையர்கள் யாரும் சேர்க்கப்படவில்லை.",
        "no_transactions" to "பரிவர்த்தனைகள் எதுவும் பதிவு செய்யப்படவில்லை.",
        "record_purchase" to "கொள்முதல் பதிவு (-)",
        "record_payment" to "பணம் செலுத்திய பதிவு (+)",
        "stock_alert" to "குறைந்த சரக்கு எச்சரிக்கை!",
        "add_product" to "புதிய தயாரிப்பு சேர்",
        "product_name" to "தயாரிப்பு பெயர்",
        "category" to "வகை",
        "selling_price" to "விலை (₹)",
        "stock_qty" to "ஆரம்ப சரக்கு",
        "low_stock_limit" to "குறைந்தபட்ச சரக்கு வரம்பு",
        "barcode" to "பார்கோடு (விருப்பம்)",
        "total_stock" to "மொத்த சரக்கு",
        "gst_billing" to "ஜிஎஸ்டி பில்லிங்",
        "create_invoice" to "இன்வாய்ஸ் உருவாக்கு",
        "invoice_no" to "இன்வாய்ஸ் எண்",
        "gst_rate" to "ஜிஎஸ்டி சதவீதம் (%)",
        "include_gst" to "ஜிஎஸ்டி சேர்",
        "total_amount" to "துணைத் தொகை",
        "share_whatsapp" to "வாட்ஸ்அப்பில் பகிர்க",
        "share_sms" to "எஸ்எம்எஸ் நினைவூட்டல்",
        "reminder_heading" to "கொடுப்பனவு நினைவூட்டல்",
        "business_name" to "வணிகப் பெயர்",
        "upi_id" to "UPI ஐடி",
        "gstin" to "GSTIN (விருப்பம்)",
        "profile_setting" to "வணிக அமைப்புகள்",
        "net_balance" to "நிகர இருப்பு",
        "upi_qr" to "UPI QR குறியீடு",
        "reminder_text" to "அன்பான வாடிக்கையாளரே, உங்களின் நிலுவைத் தொகை ₹%s செலுத்த வேண்டியுள்ளது. கீழே உள்ள விவரங்களைப் பயன்படுத்தி செலுத்தவும். நன்றி!",
        "switch_lang" to "மொழியை மாற்றுக",
        "gst_charge" to "ஜிஎஸ்டி வரி",
        "net_payable" to "மொத்த செலுத்த வேண்டிய தொகை",
        "unpaid" to "நிலுவை",
        "paid" to "செலுத்தப்பட்டது"
    )

    // Gujarati Translations
    private val gu = mapOf(
        "app_title" to "સ્માર્ટ ખાતા પ્રો",
        "receivable" to "કુલ લેવાના (ગ્રાહક પાસેથી)",
        "payable" to "કુલ આપવાના (સપ્લાયરને)",
        "today_tx" to "આજના વ્યવહારો",
        "monthly_summary" to "માસિક સારાંશ",
        "quick_add" to "ગ્રાહક ઉમેરો",
        "add_customer" to "નવો ગ્રાહક ઉમેરો",
        "add_supplier" to "નવો સપ્લાયર ઉમેરો",
        "dashboard_tab" to "ડેશબોર્ડ",
        "customers_tab" to "ગ્રાહક ખાતું",
        "suppliers_tab" to "સપ્લાયર્સ",
        "inventory_tab" to "સ્ટોક યાદી",
        "billing_tab" to "બિલિંગ અને ઇનવોઇસ",
        "profile_tab" to "દુકાન પ્રોફાઇલ",
        "customer_name" to "ગ્રાહકનું નામ",
        "supplier_name" to "સપ્લાયરનું નામ",
        "phone_number" to "મોબાઇલ નંબર",
        "address" to "સરનામું",
        "save" to "સાચવો",
        "cancel" to "રદ કરો",
        "delete" to "કાઢી નાખો",
        "edit" to "સુધારો",
        "udhar_khata" to "ઉધાર ખાત બહી",
        "give_credit" to "ઉધાર આપ્યા (આઉટ / -)",
        "receive_payment" to "જમા મળ્યા (ઇન / +)",
        "remaining_bal" to "બાકી રકમ",
        "amount" to "રકમ (₹)",
        "notes" to "વિગતો (વસ્તુઓ / નોટ્સ)",
        "add_transaction" to "વ્યવહાર ઉમેરો",
        "search_hint" to "નામ કે નંબરથી શોધો...",
        "no_customers" to "હજી સુધી કોઈ ગ્રાહક ઉમેરાયો નથી.",
        "no_suppliers" to "હજી સુધી કોઈ સપ્લાયર ઉમેરાયો નથી.",
        "no_transactions" to "હજી સુધી કોઈ વ્યવહાર નોંધાયો નથી.",
        "record_purchase" to "ખરીદી નોંધણી (-)",
        "record_payment" to "ચુકવણી નોંધણી (+)",
        "stock_alert" to "ઓછા સ્ટોકની ચેતવણી!",
        "add_product" to "નવી પ્રોડક્ટ ઉમેરો",
        "product_name" to "પ્રોડક્ટનું નામ",
        "category" to "કેટેગરી",
        "selling_price" to "કિંમત (₹)",
        "stock_qty" to "શરૂઆતનો સ્ટોક શિલાલ",
        "low_stock_limit" to "ન્યૂનતમ સ્ટોક મર્યાદા",
        "barcode" to "બારકોડ (વૈકલ્પિક)",
        "total_stock" to "કુલ સ્ટોક",
        "gst_billing" to "જીએસટી બિલિંગ",
        "create_invoice" to "ઇનવોઇસ બનાવો",
        "invoice_no" to "ઇનવોઇસ નંબર",
        "gst_rate" to "જીએસટી દર (%)",
        "include_gst" to "જીએસટી ઉમેરો",
        "total_amount" to "પેટા સરવાળો",
        "share_whatsapp" to "વોટ્સએપ પર શેર કરો",
        "share_sms" to "SMS રીમાઇન્ડર",
        "reminder_heading" to "ચુકવણી રીમાઇન્ડર",
        "business_name" to "વ્યાપારનું નામ",
        "upi_id" to "UPI આઈડી",
        "gstin" to "GSTIN (વૈકલ્પિક)",
        "profile_setting" to "વ્યાપાર સેટિંગ્સ",
        "net_balance" to "ચોખ્ખી બાકી રકમ",
        "upi_qr" to "UPI QR કોડ",
        "reminder_text" to "પ્રિય ગ્રાહક, તમારી ₹%s ની બાકી રકમ ચુકવવાની બાકી છે. કૃપા કરીને નીચેની વિગતો દ્વારા ચુકવણી કરો. આભાર!",
        "switch_lang" to "ભાષા બદલો",
        "gst_charge" to "જીએસટી ટેક્સ",
        "net_payable" to "કુલ ચુકવવાપાત્ર રકમ",
        "unpaid" to "બાકી",
        "paid" to "ચુકવી દીધું"
    )

    // Urdu Translations
    private val ur = mapOf(
        "app_title" to "اسمارٹ کھاتہ پرو",
        "receivable" to "کل قابل وصول (آپ کو ملے گا)",
        "payable" to "کل قابل ادائیگی (آپ کو دینا ہے)",
        "today_tx" to "آج کے لین دین",
        "monthly_summary" to "ماہانہ خلاصہ",
        "quick_add" to "گاہک شامل کریں",
        "add_customer" to "نیا گاہک شامل کریں",
        "add_supplier" to "نیا سپلائر شامل کریں",
        "dashboard_tab" to "ڈیش بورڈ",
        "customers_tab" to "گاہک کھاتہ",
        "suppliers_tab" to "سپلائرز",
        "inventory_tab" to "اسٹاک لسٹ",
        "billing_tab" to "بلنگ اور انوائس",
        "profile_tab" to "دکان کی تفصیلات",
        "customer_name" to "گاہک کا نام",
        "supplier_name" to "سپلائر کا نام",
        "phone_number" to "موبائل نمبر",
        "address" to "پتہ",
        "save" to "محفوظ کریں",
        "cancel" to "منسوخ کریں",
        "delete" to "حذف کریں",
        "edit" to "ترمیم کریں",
        "udhar_khata" to "ادھار کھاتہ رجسٹر",
        "give_credit" to "ادھار دیا (آؤٹ / -)",
        "receive_payment" to "رقم وصول کی (اِن / +)",
        "remaining_bal" to "بقایا رقم",
        "amount" to "رقم (₹)",
        "notes" to "تفصیل (سامان / نوٹس)",
        "add_transaction" to "لین دین درج کریں",
        "search_hint" to "نام یا نمبر سے تلاش کریں...",
        "no_customers" to "ابھی تک کوئی گاہک شامل نہیں کیا گیا۔",
        "no_suppliers" to "ابھی تک کوئی سپلائر شامل نہیں کیا گیا۔",
        "no_transactions" to "ابھی کوئی لین دین درج نہیں کیا گیا۔",
        "record_purchase" to "خریداری درج کریں (-)",
        "record_payment" to "ادائیگی درج کریں (+)",
        "stock_alert" to "اسٹاک ختم ہونے کا الرٹ!",
        "add_product" to "نئی پروڈکٹ شامل کریں",
        "product_name" to "پروڈکٹ کا نام",
        "category" to "کیٹیگری",
        "selling_price" to "قیمت (₹)",
        "stock_qty" to "ابتدائی اسٹاک تعداد",
        "low_stock_limit" to "کم از کم اسٹاک کی حد",
        "barcode" to "بارکوڈ (اختیاری)",
        "total_stock" to "کل اسٹاک",
        "gst_billing" to "جی ایس ٹی بلنگ",
        "create_invoice" to "انوائس بنائیں",
        "invoice_no" to "انوائس نمبر",
        "gst_rate" to "GST شرح (%)",
        "include_gst" to "جی ایس ٹی شامل کریں",
        "total_amount" to "ذیلی کل",
        "share_whatsapp" to "واٹس ایپ پر شیئر کریں",
        "share_sms" to "SMS یاد دہانی",
        "reminder_heading" to "رقم کی یاد دہانی",
        "business_name" to "کاروبار کا نام",
        "upi_id" to "UPI آئی ڈی",
        "gstin" to "GSTIN (اختیاری)",
        "profile_setting" to "کاروباری سیٹنگز",
        "net_balance" to "کل بقایا",
        "upi_qr" to "UPI QR کوڈ",
        "reminder_text" to "محترم گاہک، آپ کا بقایا ادھار ₹%s قابل ادائیگی ہے۔ مہربانی فرما کر نیچے دی گئی تفصیلات کے مطابق ادائیگی کریں۔ شکریہ!",
        "switch_lang" to "زبان تبدیل کریں",
        "gst_charge" to "جی ایس ٹی ٹیکس",
        "net_payable" to "کل واجب الادا رقم",
        "unpaid" to "بقایا",
        "paid" to "ادا شدہ"
    )

    // Kannada Translations
    private val kn = mapOf(
        "app_title" to "ಸ್ಮಾರ್ಟ್ ಖಾತಾ ಪ್ರೊ",
        "receivable" to "ಒಟ್ಟು ಬರಬೇಕಾದದ್ದು (ನಿಮಗೆ ಬರುವುದು)",
        "payable" to "ಒಟ್ಟು ಕೊಡಬೇಕಾದದ್ದು (ನೀವು ಕೊಡುವುದು)",
        "today_tx" to "ಇಂದಿನ ವಹಿವಾಟುಗಳು",
        "monthly_summary" to "ತಿಂಗಳ ಸಾರಾಂಶ",
        "quick_add" to "ಗ್ರಾಹಕನನ್ನು ಸೇರಿಸಿ",
        "add_customer" to "ಹೊಸ ಗ್ರಾಹಕನನ್ನು ಸೇರಿಸಿ",
        "add_supplier" to "ಹೊಸ ಸರಬರಾಜುದಾರನನ್ನು ಸೇರಿಸಿ",
        "dashboard_tab" to "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        "customers_tab" to "ಗ್ರಾಹಕ ಖಾತೆ",
        "suppliers_tab" to "ಸರಬರಾಜುದಾರರು",
        "inventory_tab" to "ದಾಸ್ತಾನು",
        "billing_tab" to "ಬಿಲ್ಲಿಂಗ್ ಮತ್ತು ಇನ್‌ವಾಯ್ಸ್",
        "profile_tab" to "ಅಂಗಡಿ ಪ್ರೊಫೈಲ್",
        "customer_name" to "ಗ್ರಾಹಕನ ಹೆಸರು",
        "supplier_name" to "ಸರಬರಾಜುದಾರನ ಹೆಸರು",
        "phone_number" to "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
        "address" to "ವಿಳಾಸ",
        "save" to "ಉಳಿಸು",
        "cancel" to "ರದ್ದುಮಾಡು",
        "delete" to "ಅಳಿಸು",
        "edit" to "ತಿದ್ದುಪಡಿ",
        "udhar_khata" to "ಉದ್ರಿ ಬರೆಹ ಪುಸ್ತಕ",
        "give_credit" to "ಉದ್ರಿ ನೀಡಿ (ಔಟ್ / -)",
        "receive_payment" to "ಹಣ ಪಡೆಯಿರಿ (ಇನ್ / +)",
        "remaining_bal" to "ಉಳಿಕೆ ಬಾಕಿ",
        "amount" to "ಮೊತ್ತ (₹)",
        "notes" to "ವಿವರಗಳು (ವಸ್ತುಗಳು / ಟಿಪ್ಪಣಿಗಳು)",
        "add_transaction" to "ವಹಿವಾಟು ಸೇರಿಸಿ",
        "search_hint" to "ಹೆಸರು ಅಥವಾ ಸಂಖ್ಯೆಯಿಂದ ಹುಡುಕಿ...",
        "no_customers" to "ಇನ್ನೂ ಯಾವುದೇ ಗ್ರಾಹಕರನ್ನು ಸೇರಿಸಿಲ್ಲ.",
        "no_suppliers" to "ಇನ್ನೂ ಯಾವುದೇ ಸರಬರಾಜುದಾರರನ್ನು ಸೇರಿಸಿಲ್ಲ.",
        "no_transactions" to "ಯಾವುದೇ ವಹಿವಾಟುಗಳು ದಾಖಲಾಗಿಲ್ಲ.",
        "record_purchase" to "ಖರೀದಿ ದಾಖಲಿಸಿ (-)",
        "record_payment" to "ಪಾವತಿ ದಾಖಲಿಸಿ (+)",
        "stock_alert" to "ಕಡಿಮೆ ದಾಸ್ತಾನು ಎಚ್ಚರಿಕೆ!",
        "add_product" to "ಹೊಸ ಉತ್ಪನ್ನ ಸೇರಿಸಿ",
        "product_name" to "ಉತ್ಪನ್ನದ ಹೆಸರು",
        "category" to "ವರ್ಗ",
        "selling_price" to "ಬೆಲೆ (₹)",
        "stock_qty" to "ಪ್ರಾರಂಭಿಕ ದಾಸ್ತಾನು",
        "low_stock_limit" to "ಕನಿಷ್ಠ ದಾಸ್ತಾನು ಮಿತಿ",
        "barcode" to "ಬಾರ್‌ಕೋಡ್ (ಐಚ್ಛಿಕ)",
        "total_stock" to "ಒಟ್ಟು ದಾಸ್ತಾನು",
        "gst_billing" to "ಜಿಎಸ್ಟಿ ಬಿಲ್ಲಿಂಗ್",
        "create_invoice" to "ಇನ್‌ವಾಯ್ಸ್ ರಚಿಸಿ",
        "invoice_no" to "ಇನ್‌ವಾಯ್ಸ್ ಸಂಖ್ಯೆ",
        "gst_rate" to "ಜಿಎಸ್ಟಿ ದರ (%)",
        "include_gst" to "ಜಿಎಸ್ಟಿ ಸೇರಿಸಿ",
        "total_amount" to "ಉಪ ಮೊತ್ತ",
        "share_whatsapp" to "ವಾಟ್ಸಾಪ್ ಉದ್ಧರಣೆ",
        "share_sms" to "SMS ನೆನಪೋಲೆ",
        "reminder_heading" to "ಪಾವತಿ ಜ್ಞಾಪನೆ",
        "business_name" to "ವ್ಯಾಪಾರದ ಹೆಸರು",
        "upi_id" to "UPI ಐಡಿ",
        "gstin" to "GSTIN (ಐಚ್ಛಿಕ)",
        "profile_setting" to "ವ್ಯಾಪಾರ ಸೆಟ್ಟಿಂಗ್ಸ್",
        "net_balance" to "ನಿವ್ವಳ ಬಾಕಿ",
        "upi_qr" to "UPI QR ಕೋಡ್",
        "reminder_text" to "ಆತ್ಮೀಯ ಗ್ರಾಹಕರೇ, ನಿಮ್ಮ ಬಾಕಿ ಪಾವತಿ ₹%s ಪಾವತಿಸಬೇಕಿದೆ. ದಯವಿಟ್ಟು ಕೆಳಗಿನ ವಿವರಗಳ ಮೂಲಕ ಪಾವತಿಸಿ. ಧನ್ಯವಾದಗಳು!",
        "switch_lang" to "ಭಾಷೆ ಬದಲಿಸಿ",
        "gst_charge" to "ಜಿಎಸ್ಟಿ ತೆರಿಗೆ",
        "net_payable" to "ಒಟ್ಟು ಪಾವತಿಸಬೇಕಾದದ್ದು",
        "unpaid" to "ಬಾಕಿ",
        "paid" to "ಪಾವತಿಸಲಾಗಿದೆ"
    )

    // Malayalam Translations
    private val ml = mapOf(
        "app_title" to "സ്മാർട്ട് ഖാത്ത പ്രോ",
        "receivable" to "ആകെ ലഭിക്കാനുള്ളത് (നിങ്ങൾക്ക് കിട്ടാനുള്ളത്)",
        "payable" to "ആകെ നൽകാനുള്ളത് (നിങ്ങൾ നൽകാനുള്ളത്)",
        "today_tx" to "ഇന്നത്തെ ഇടപാടുകൾ",
        "monthly_summary" to "പ്രതിമാസ സംഗ്രഹം",
        "quick_add" to "ഉപഭോക്താവിനെ ചേർക്കുക",
        "add_customer" to "പുതിയ ഉപഭോക്താവിനെ ചേർക്കു",
        "add_supplier" to "പുതിയ സപ്ലയറെ ചേർക്കുക",
        "dashboard_tab" to "ഡാഷ്‌ബോർഡ്",
        "customers_tab" to "ഉപഭോക്തൃ ഖാത്ത",
        "suppliers_tab" to "സപ്ലയർമാർ",
        "inventory_tab" to "സ്റ്റോക്ക് വിവരങ്ങൾ",
        "billing_tab" to "ബില്ലിംഗും ഇൻവോയ്സും",
        "profile_tab" to "ഷോപ്പ് പ്രൊഫൈൽ",
        "customer_name" to "ഉപഭോക്താവിന്റെ പേര്",
        "supplier_name" to "സപ്ലയറുടെ പേര്",
        "phone_number" to "മൊബൈൽ നമ്പർ",
        "address" to "മേൽവിലാസം",
        "save" to "സൂക്ഷിക്കുക",
        "cancel" to "റദ്ദാക്കുക",
        "delete" to "ഒഴിവാക്കുക",
        "edit" to "തിരുത്തുക",
        "udhar_khata" to "കടം ഇടപാട് ബുക്ക്",
        "give_credit" to "കടം നൽകുക (ഔട്ട് / -)",
        "receive_payment" to "പണം സ്വീകരിക്കുക (ഇൻ / +)",
        "remaining_bal" to "ബാക്കി തുക",
        "amount" to "തുക (₹)",
        "notes" to "വിശദാംശങ്ങൾ (വിവരങ്ങൾ/കുറിപ്പുകൾ)",
        "add_transaction" to "ഇടപാട് ചേർക്കുക",
        "search_hint" to "പേരോ നമ്പറോ ഉപയോഗിച്ച് തിരയുക...",
        "no_customers" to "ഉപഭോക്താക്കളെ ആരെയും ചേർത്തിട്ടില്ല.",
        "no_suppliers" to "സപ്ലയർമാരെ ആരെയും ചേർത്തിട്ടില്ല.",
        "no_transactions" to "ഇടപാടുകൾ ഒന്നും രേഖപ്പെടുത്തിയിട്ടില്ല.",
        "record_purchase" to "വാങ്ങൽ രേഖപ്പെടുത്തുക (-)",
        "record_payment" to "പേയ്മെന്റ് രേഖപ്പെടുത്തുക (+)",
        "stock_alert" to "കുറഞ്ഞ സ്റ്റോക്ക് മുന്നറിയിപ്പ്!",
        "add_product" to "പുതിയ ഉൽപ്പന്നം ചേർക്കുക",
        "product_name" to "ഉൽപ്പന്നത്തിന്റെ പേര്",
        "category" to "വിഭാഗം",
        "selling_price" to "വില (₹)",
        "stock_qty" to "തുടക്ക സ്റ്റോക്ക്",
        "low_stock_limit" to "കുറഞ്ഞ സ്റ്റോക്ക് പരിധി",
        "barcode" to "ബാർകോഡ് (നിർബന്ധമില്ലാത്തത്)",
        "total_stock" to "ആകെ സ്റ്റോക്ക്",
        "gst_billing" to "ജിഎസ്ടി ബില്ലിംഗ്",
        "create_invoice" to "ഇൻവോയ്സ് ഉണ്ടാക്കുക",
        "invoice_no" to "ഇൻവോയ്സ് നമ്പർ",
        "gst_rate" to "ജിഎസ്ടി നിരക്ക് (%)",
        "include_gst" to "ജിഎസ്ടി ഉൾപ്പെടുത്തുക",
        "total_amount" to "സബ്‌ ടോട്ടൽ",
        "share_whatsapp" to "വാട്സാപ്പിലൂടെ പങ്കുവെക്കുക",
        "share_sms" to "SMS ഓർമ്മപ്പെടുത്തൽ",
        "reminder_heading" to "പേയ്മെന്റ് ഓർമ്മപ്പെടുത്തൽ",
        "business_name" to "ബിസിനസ്സിന്റെ പേര്",
        "upi_id" to "UPI ഐഡി",
        "gstin" to "GSTIN (നിർബന്ധമില്ലാത്തത്)",
        "profile_setting" to "ബിസിനസ്സ് ക്രമീകരണങ്ങൾ",
        "net_balance" to "നെറ്റ് ബാലൻസ്",
        "upi_qr" to "UPI QR കോഡ്",
        "reminder_text" to "പ്രിയ ഉപഭോക്താവേ, നിങ്ങളുടെ ₹%s കുടിശ്ശിക പേയ്‌മെന്റ് ബാക്കിയുണ്ട്. ദയവായി താഴെ പറയുന്ന വിശദാംശങ്ങൾ ഉപയോഗിച്ച് പണമടയ്ക്കുക. നന്ദി!",
        "switch_lang" to "ഭാഷ മാറ്റുക",
        "gst_charge" to "ജിഎസ്ടി നികുതി",
        "net_payable" to "ആകെ നൽകേണ്ട തുക",
        "unpaid" to "ബാക്കി",
        "paid" to "അടച്ചുതീർത്തത്"
    )

    // Punjabi Translations
    private val pa = mapOf(
        "app_title" to "ਸਮਾਰਟ ਖਾਤਾ ਪ੍ਰੋ",
        "receivable" to "ਕੁੱਲ ਲੈਣਾ (ਗਾਹਕ ਤੋਂ)",
        "payable" to "ਕੁੱਲ ਦੇਣਾ (ਸਪਲਾਇਰ ਨੂੰ)",
        "today_tx" to "ਅੱਜ ਦੇ ਲੈਣ-ਦੇਣ",
        "monthly_summary" to "ਮਹੀਨਾਵਾਰ ਸਾਰਾਂਸ਼",
        "quick_add" to "ਗਾਹਕ ਜੋੜੋ",
        "add_customer" to "ਨਵਾਂ ਗਾਹਕ ਜੋੜੋ",
        "add_supplier" to "ਨਵਾਂ ਸਪਲਾਇਰ ਜੋੜੋ",
        "dashboard_tab" to "ਡੈਸ਼ਬੋਰਡ",
        "customers_tab" to "ਗਾਹਕ ਖਾਤਾ",
        "suppliers_tab" to "ਸਪਲਾਇਰ",
        "inventory_tab" to "ਸਟਾਕ ਮਾਲ",
        "billing_tab" to "ਬਿਲਿੰਗ ਅਤੇ ਇਨਵੌਇਸ",
        "profile_tab" to "ਦੁਕਾਨ ਪ੍ਰੋਫਾਈਲ",
        "customer_name" to "ਗਾਹਕ ਦਾ ਨਾਮ",
        "supplier_name" to "ਸਪਲਾਇਰ ਦਾ ਨਾਮ",
        "phone_number" to "ਮੋਬਾਈਲ ਨੰਬਰ",
        "address" to "ਦੁਕਾਨ/ਘਰ ਦਾ ਪਤਾ",
        "save" to "ਸੁਰੱਖਿਅਤ ਕਰੋ",
        "cancel" to "ਰੱਦ ਕਰੋ",
        "delete" to "ਹਟਾਓ",
        "edit" to "ਬਦਲੋ",
        "udhar_khata" to "ਉਧਾਰ ਖਾਤਾ ਲੈਜਰ",
        "give_credit" to "ਉਧਾਰ ਦਿੱਤਾ (ਆਉਟ / -)",
        "receive_payment" to "ਜਮ੍ਹਾ ਮਿਲਿਆ (ਇਨ / +)",
        "remaining_bal" to "ਕੁੱਲ ਬਾਕੀ ਬਕਾਇਆ",
        "amount" to "ਰਕਮ (₹)",
        "notes" to "ਸਾਮਾਨ ਦਾ ਵੇਰਵਾ / ਨੋਟ",
        "add_transaction" to "ਲੈਣ-ਦੇਣ ਜੋੜੋ",
        "search_hint" to "ਨਾਮ ਜਾਂ ਨੰਬਰ ਨਾਲ ਲੱਭੋ...",
        "no_customers" to "ਅਜੇ ਤੱਕ ਕੋਈ ਗਾਹਕ ਨਹੀਂ ਜੋੜਿਆ ਗਿਆ।",
        "no_suppliers" to "ਅਜੇ ਤੱਕ ਕੋਈ ਸਪਲਾਇਰ ਨਹੀਂ ਜੋੜਿਆ ਗਿਆ।",
        "no_transactions" to "ਕੋਈ ਲੈਣ-ਦੇਣ ਦਰਜ ਨਹੀਂ ਹੈ।",
        "record_purchase" to "ਖਰੀਦਦਾਰੀ ਦਰਜ ਕਰੋ (-)",
        "record_payment" to "ਭੁਗਤਾਨ ਦਰਜ ਕਰੋ (+)",
        "stock_alert" to "ਘੱਟ ਸਟਾਕ ਚੇਤਾਵਨੀ!",
        "add_product" to "ਨਵਾਂ ਉਤਪਾਦ ਜੋੜੋ",
        "product_name" to "ਉਤਪਾਦ ਦਾ ਨਾਮ",
        "category" to "ਸ਼੍ਰੇਣੀ (ਕੈਟੇਗਰੀ)",
        "selling_price" to "ਕੀਮਤ (₹)",
        "stock_qty" to "ਸ਼ੁਰੂਆਤੀ ਸਟਾਕ ਗਿਣਤੀ",
        "low_stock_limit" to "ਘੱಟੋ ਘੱਟ ਸਟਾਕ ਸੀਮਾ",
        "barcode" to "ਬਾਰਕੋਡ (ਵਿਕਲਪਿਕ)",
        "total_stock" to "ਕੁੱਲ ਸਟਾਕ",
        "gst_billing" to "ਜੀਐਸਟੀ ਬਿਲਿੰਗ",
        "create_invoice" to "ਇਨਵੌਇਸ ਬਣਾਓ",
        "invoice_no" to "ਇਨਵੌਇਸ ਨੰਬਰ",
        "gst_rate" to "GST ਦਰ (%)",
        "include_gst" to "ਜੀਐਸਟੀ ਸ਼ਾਮਲ ਕਰੋ",
        "total_amount" to "ਉਪ ਜੋੜ (SubTotal)",
        "share_whatsapp" to "ਵਟਸਐਪ 'ਤੇ ਸ਼ੇਅਰ ਕਰੋ",
        "share_sms" to "SMS ਰੀਮਾਈਂਡਰ",
        "reminder_heading" to "ਭੁਗਤਾਨ ਰੀਮਾਈਂਡਰ",
        "business_name" to "ਕਾਰੋਬਾਰ ਦਾ ਨਾਮ",
        "upi_id" to "UPI ਆਈਡੀ",
        "gstin" to "GSTIN (ਵਿਕਲਪਿਕ)",
        "profile_setting" to "ਦੁਕਾਨ ਸੈਟਿੰਗਜ਼",
        "net_balance" to "ਸ਼ੁੱਧ ਬਕਾਇਆ",
        "upi_qr" to "UPI QR ਕੋਡ",
        "reminder_text" to "ਪਿਆਰੇ ਗਾਹਕ, ਤੁਹਾਡੀ ₹%s ਦੀ ਬਾਕੀ ਰਕਮ ਦੇਣੀ ਬਾਕੀ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ ਹੇਠਾਂ ਦਿੱਤੇ ਵੇਰਵਿਆਂ ਦੀ ਵਰਤੋਂ ਕਰਕੇ ਭੁਗਤਾਨ ਕਰੋ। ਧੰਨਵਾਦ!",
        "switch_lang" to "ਭਾਸ਼ਾ ਬਦਲੋ",
        "gst_charge" to "जीਐਸਟੀ ਟੈਕਸ",
        "net_payable" to "ਕੁੱਲ ਦੇਣਯੋਗ ਰਕਮ",
        "unpaid" to "ਬਾਕੀ ਬਕਾਇਆ",
        "paid" to "ਭੁਗਤਾਨ ਹੋ ਚੁੱਕਾ"
    )

    fun t(key: String, lang: Language): String {
        val map = when (lang) {
            Language.ENGLISH -> en
            Language.HINDI -> hi
            Language.BENGALI -> bn
            Language.TELUGU -> te
            Language.MARATHI -> mr
            Language.TAMIL -> ta
            Language.GUJARATI -> gu
            Language.URDU -> ur
            Language.KANNADA -> kn
            Language.MALAYALAM -> ml
            Language.PUNJABI -> pa
        }
        return map[key] ?: en[key] ?: key
    }
}
